INSERT INTO PURCHASE_LIST (LIST_NAME) VALUES ('Eletrônicos');
INSERT INTO ITEM (NAME, QUANTITY, PURCHASE_LIST_ID) VALUES ('Celulares', 3, 1);
INSERT INTO ITEM (NAME, QUANTITY, PURCHASE_LIST_ID) VALUES ('Computadores', 5, 1);

INSERT INTO PURCHASE_LIST (LIST_NAME) VALUES ('Alimentos');
INSERT INTO ITEM (NAME, QUANTITY, PURCHASE_LIST_ID) VALUES ('Maçãs', 10, 2);
INSERT INTO ITEM (NAME, QUANTITY, PURCHASE_LIST_ID) VALUES ('Bananas', 15, 2);